-- MySQL Script generated by MySQL Workbench
-- 10/24/17 18:08:15
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_semear
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_semear
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_semear` DEFAULT CHARACTER SET utf8 ;
USE `db_semear` ;

-- -----------------------------------------------------
-- Table `db_semear`.`tb_instituicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_semear`.`tb_instituicao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_semear`.`tb_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_semear`.`tb_curso` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  `modalidade` VARCHAR(45) NOT NULL,
  `grau` VARCHAR(45) NOT NULL,
  `fk_tb_instituicao_id` INT NOT NULL,
  PRIMARY KEY (`id`, `fk_tb_instituicao_id`),
  INDEX `fk_tb_instituicao1_id` (`fk_tb_instituicao_id` ASC),
  CONSTRAINT `fk_tb_instituicao1`
    FOREIGN KEY (`fk_tb_instituicao_id`)
    REFERENCES `db_semear`.`tb_instituicao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_semear`.`tb_disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_semear`.`tb_disciplina` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_semear`.`tb_disciplina_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_semear`.`tb_disciplina_curso` (
  `fk_tb_disciplina_id` INT NOT NULL,
  `fk_tb_curso_id` INT NOT NULL,
  `periodo` INT NOT NULL,
  PRIMARY KEY (`fk_tb_disciplina_id`, `fk_tb_curso_id`),
  INDEX `fk_tb_curso2_id` (`fk_tb_curso_id` ASC),
  INDEX `fk_tb_disciplina1_id` (`fk_tb_disciplina_id` ASC),
  CONSTRAINT `fk_tb_disciplina1`
    FOREIGN KEY (`fk_tb_disciplina_id`)
    REFERENCES `db_semear`.`tb_disciplina` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_curso2`
    FOREIGN KEY (`fk_tb_curso_id`)
    REFERENCES `db_semear`.`tb_curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_semear`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_semear`.`tb_usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sobrenome` VARCHAR(80) NOT NULL,
  `nome_usuario` VARCHAR(45) NOT NULL,
  `email` VARCHAR(120) NOT NULL,
  `senha` VARCHAR(150) NOT NULL,
  `dt_nascimento` DATE NOT NULL,
  `sexo` VARCHAR(45) NOT NULL,
  `dt_cadastro` DATETIME NOT NULL,
  `status` BIT(1) NOT NULL,
  `link_foto_perfil` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_usuario_UNIQUE` (`nome_usuario` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_semear`.`tb_aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_semear`.`tb_aluno` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fk_tb_usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_usuario3_id` (`fk_tb_usuario_id` ASC),
  CONSTRAINT `fk_tb_usuario3`
    FOREIGN KEY (`fk_tb_usuario_id`)
    REFERENCES `db_semear`.`tb_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_semear`.`tb_usuario_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_semear`.`tb_usuario_curso` (
  `fk_tb_usuario_id` INT NOT NULL,
  `fk_tb_curso_id` INT NOT NULL,
  PRIMARY KEY (`fk_tb_usuario_id`, `fk_tb_curso_id`),
  INDEX `fk_tb_curso1_id` (`fk_tb_curso_id` ASC),
  INDEX `fk_tb_usuario4_id` (`fk_tb_usuario_id` ASC),
  CONSTRAINT `fk_tb_usuario4`
    FOREIGN KEY (`fk_tb_usuario_id`)
    REFERENCES `db_semear`.`tb_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_curso1`
    FOREIGN KEY (`fk_tb_curso_id`)
    REFERENCES `db_semear`.`tb_curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_semear`.`tb_administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_semear`.`tb_administrador` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fk_tb_usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_usuario1_id` (`fk_tb_usuario_id` ASC),
  CONSTRAINT `fk_tb_usuario1`
    FOREIGN KEY (`fk_tb_usuario_id`)
    REFERENCES `db_semear`.`tb_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_semear`.`tb_administrador_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_semear`.`tb_administrador_curso` (
  `fk_tb_administrador_id` INT NOT NULL,
  `fk_tb_curso_id` INT NOT NULL,
  PRIMARY KEY (`fk_tb_administrador_id`, `fk_tb_curso_id`),
  INDEX `fk_tb_curso3_id` (`fk_tb_curso_id` ASC),
  INDEX `fk_tb_administrador1_id` (`fk_tb_administrador_id` ASC),
  CONSTRAINT `fk_tb_administrador1`
    FOREIGN KEY (`fk_tb_administrador_id`)
    REFERENCES `db_semear`.`tb_administrador` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_curso3`
    FOREIGN KEY (`fk_tb_curso_id`)
    REFERENCES `db_semear`.`tb_curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_semear`.`tb_moderador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_semear`.`tb_moderador` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fk_tb_usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_usuario2_id` (`fk_tb_usuario_id` ASC),
  CONSTRAINT `fk_tb_usuario2`
    FOREIGN KEY (`fk_tb_usuario_id`)
    REFERENCES `db_semear`.`tb_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_semear`.`tb_moderador_disciplina_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_semear`.`tb_moderador_disciplina_curso` (
  `fk_tb_moderador_id` INT NOT NULL,
  `fk_tb_disciplina_curso_tb_disciplina_id` INT NOT NULL,
  `fk_tb_disciplina_curso_tb_curso_id` INT NOT NULL,
  PRIMARY KEY (`fk_tb_moderador_id`, `fk_tb_disciplina_curso_tb_disciplina_id`, `fk_tb_disciplina_curso_tb_curso_id`),
  INDEX `fk_tb_disciplina_curso1_id` (`fk_tb_disciplina_curso_tb_disciplina_id` ASC, `fk_tb_disciplina_curso_tb_curso_id` ASC),
  INDEX `fk_tb_moderador1_id` (`fk_tb_moderador_id` ASC),
  CONSTRAINT `fk_tb_moderador1`
    FOREIGN KEY (`fk_tb_moderador_id`)
    REFERENCES `db_semear`.`tb_moderador` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_disciplina_curso1`
    FOREIGN KEY (`fk_tb_disciplina_curso_tb_disciplina_id` , `fk_tb_disciplina_curso_tb_curso_id`)
    REFERENCES `db_semear`.`tb_disciplina_curso` (`fk_tb_disciplina_id` , `fk_tb_curso_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_semear`.`tb_aluno_disciplina_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_semear`.`tb_aluno_disciplina_curso` (
  `fk_tb_aluno_id` INT NOT NULL,
  `fk_tb_disciplina_curso_tb_disciplina_id` INT NOT NULL,
  `fk_tb_disciplina_curso_tb_curso_id` INT NOT NULL,
  `permicao_publicacao` BIT(1) NULL,
  PRIMARY KEY (`fk_tb_aluno_id`, `fk_tb_disciplina_curso_tb_disciplina_id`, `fk_tb_disciplina_curso_tb_curso_id`),
  INDEX `fk_tb_disciplina_curso2_id` (`fk_tb_disciplina_curso_tb_disciplina_id` ASC, `fk_tb_disciplina_curso_tb_curso_id` ASC),
  INDEX `fk_tb_aluno4_id` (`fk_tb_aluno_id` ASC),
  CONSTRAINT `fk_tb_aluno4`
    FOREIGN KEY (`fk_tb_aluno_id`)
    REFERENCES `db_semear`.`tb_aluno` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_disciplina_curso2`
    FOREIGN KEY (`fk_tb_disciplina_curso_tb_disciplina_id` , `fk_tb_disciplina_curso_tb_curso_id`)
    REFERENCES `db_semear`.`tb_disciplina_curso` (`fk_tb_disciplina_id` , `fk_tb_curso_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_semear`.`tb_pubicacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_semear`.`tb_pubicacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fk_tb_aluno_id` INT NOT NULL,
  `titulo` VARCHAR(80) NOT NULL,
  `descricao` TEXT NOT NULL,
  `tags` VARCHAR(255) NOT NULL,
  `link_arquivo` VARCHAR(255) NOT NULL,
  `fk_tb_moderador_id` INT NULL,
  `status` BIT(1) NOT NULL,
  PRIMARY KEY (`id`, `fk_tb_aluno_id`),
  INDEX `fk_tb_aluno3_id` (`fk_tb_aluno_id` ASC),
  INDEX `fk_tb_moderador3_id` (`fk_tb_moderador_id` ASC),
  CONSTRAINT `fk_tb_aluno3`
    FOREIGN KEY (`fk_tb_aluno_id`)
    REFERENCES `db_semear`.`tb_aluno` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_moderador3`
    FOREIGN KEY (`fk_tb_moderador_id`)
    REFERENCES `db_semear`.`tb_moderador` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_semear`.`tb_avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_semear`.`tb_avaliacao` (
  `fk_tb_aluno_id` INT NOT NULL,
  `fk_tb_pubicacao_id` INT NOT NULL,
  `nota` INT NOT NULL,
  PRIMARY KEY (`fk_tb_aluno_id`, `fk_tb_pubicacao_id`),
  INDEX `fk_tb_pubicacao1_id` (`fk_tb_pubicacao_id` ASC),
  INDEX `fk_tb_aluno1_id` (`fk_tb_aluno_id` ASC),
  CONSTRAINT `fk_tb_aluno1`
    FOREIGN KEY (`fk_tb_aluno_id`)
    REFERENCES `db_semear`.`tb_aluno` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_pubicacao1`
    FOREIGN KEY (`fk_tb_pubicacao_id`)
    REFERENCES `db_semear`.`tb_pubicacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_semear`.`tb_comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_semear`.`tb_comentario` (
  `fk_tb_aluno_id` INT NOT NULL,
  `fk_tb_pubicacao_id` INT NOT NULL,
  `comentario` TEXT NULL,
  PRIMARY KEY (`fk_tb_aluno_id`, `fk_tb_pubicacao_id`),
  INDEX `fk_tb_pubicacao2_id` (`fk_tb_pubicacao_id` ASC),
  INDEX `fk_tb_aluno2_id` (`fk_tb_aluno_id` ASC),
  CONSTRAINT `fk_tb_aluno2`
    FOREIGN KEY (`fk_tb_aluno_id`)
    REFERENCES `db_semear`.`tb_aluno` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_pubicacao2`
    FOREIGN KEY (`fk_tb_pubicacao_id`)
    REFERENCES `db_semear`.`tb_pubicacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_semear`.`tb_grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_semear`.`tb_grupo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  `descricao` VARCHAR(140) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_semear`.`tb_permissao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_semear`.`tb_permissao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_semear`.`tb_usuario_grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_semear`.`tb_usuario_grupo` (
  `fk_tb_usuario_id` INT NOT NULL,
  `fk_tb_grupo_id` INT NOT NULL,
  PRIMARY KEY (`fk_tb_usuario_id`, `fk_tb_grupo_id`),
  INDEX `fk_tb_grupo1_id` (`fk_tb_grupo_id` ASC),
  INDEX `fk_tb_usuario5_id` (`fk_tb_usuario_id` ASC),
  CONSTRAINT `fk_tb_usuario5`
    FOREIGN KEY (`fk_tb_usuario_id`)
    REFERENCES `db_semear`.`tb_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_grupo1`
    FOREIGN KEY (`fk_tb_grupo_id`)
    REFERENCES `db_semear`.`tb_grupo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_semear`.`tb_grupo_permissao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_semear`.`tb_grupo_permissao` (
  `fk_tb_grupo_id` INT NOT NULL,
  `fk_tb_permissao_id` INT NOT NULL,
  PRIMARY KEY (`fk_tb_grupo_id`, `fk_tb_permissao_id`),
  INDEX `fk_tb_permissao1_id` (`fk_tb_permissao_id` ASC),
  INDEX `fk_tb_grupo2_id` (`fk_tb_grupo_id` ASC),
  CONSTRAINT `fk_tb_grupo2`
    FOREIGN KEY (`fk_tb_grupo_id`)
    REFERENCES `db_semear`.`tb_grupo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_permissao1`
    FOREIGN KEY (`fk_tb_permissao_id`)
    REFERENCES `db_semear`.`tb_permissao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_semear`.`tb_usuario_permissao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_semear`.`tb_usuario_permissao` (
  `fk_tb_usuario_id` INT NOT NULL,
  `fk_tb_permissao_id` INT NOT NULL,
  PRIMARY KEY (`fk_tb_usuario_id`, `fk_tb_permissao_id`),
  INDEX `fk_tb_permissao2_id` (`fk_tb_permissao_id` ASC),
  INDEX `fk_tb_usuario6_id` (`fk_tb_usuario_id` ASC),
  CONSTRAINT `fk_tb_usuario6`
    FOREIGN KEY (`fk_tb_usuario_id`)
    REFERENCES `db_semear`.`tb_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_permissao2`
    FOREIGN KEY (`fk_tb_permissao_id`)
    REFERENCES `db_semear`.`tb_permissao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
